services:
  db:
    image: postgres:15
    container_name: pg-database
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build:
      context: .
    container_name: python-app
    depends_on:
      - db
    volumes:
      - .:/app
    working_dir: /app
    command: tail -f /dev/null

volumes:
  pgdata:
