# Generated by Django 5.2.1 on 2025-05-29 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.DateField(blank=True, default='2000-01-01', null=True),
        ),
    ]
