pipeline {
    agent any

    environment {
        GITHUB_CREDENTIALS = credentials('github-creds') // stored in Jenkins credentials
    }

    tools {
        // Optional: use Jenkins-installed Python
        python 'Python 3'
    }

    stages {
        stage('Clone Repository') {
            steps {
                git credentialsId: "${GITHUB_CREDENTIALS}", url: 'https://github.com/vik2ry/alx-backend-python.git'
            }
        }

        stage('Install Dependencies') {
            steps {
                sh 'pip install -r messaging_app/requirements.txt'
            }
        }

        stage('Run Tests') {
            steps {
                dir('messaging_app') {
                    sh 'pytest --ds=messaging_app.settings --junitxml=report.xml'
                }
            }
        }

        stage('Publish Test Results') {
            steps {
                junit 'messaging_app/report.xml'
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    dockerImage = docker.build('vik2ry/messaging_app')
                }
            }
        }

        stage('Push Docker Image') {
            steps {
                withDockerRegistry([credentialsId: 'dockerhub-creds', url: '']) {
                    script {
                        dockerImage.push('latest')
                    }
                }
            }
        }
    }

    post {
        always {
            echo 'Pipeline complete.'
        }
        failure {
            echo 'Build failed.'
        }
    }
}
